### ISSUE TITLE
Configure the aggregation time interval

### ISSUE THREAD

**Issue by MoritzSalein** [ludeknovy/jtl-reporter#142] opened 2022-02-17 15:54 UTC
Currently the charts calculate aggregation time interval themselve. But sometimes it will be helpful to see the interval less detailed. E.g. in a 10 minute run, my chart shows every 3 Second and some Miliseconds a new point in the graph. For this it will be good to set the interval in the settings with an individual value like 10 Seconds, 1 Minute or another.
It it possible to integrate such setting for the interval?

**Comment by ludeknovy** [comment] 2022-02-28 14:14
I will do some experiments with creating charts with multiple aggregation intervals, eg - one with more points, and one with fewer points.

**Comment by ludeknovy** [comment] 2022-03-11 08:47
@MoritzSalein 
I see two options here: 
1) Have scenario settings where you could set up some custom intervals
2) Define a couple of additional intervals eg - 10sec, 1 min, 10min, 30min, 1hour - and create charts on the processing, the same way its done now.

What do you think?

**Comment by MoritzSalein** [comment] 2022-03-11 13:28
> @MoritzSalein I see two options here:
> 
> 1. Have scenario settings where you could set up some custom intervals
> 2. Define a couple of additional intervals eg - 10sec, 1 min, 10min, 30min, 1hour - and create charts on the processing, the same way its done now.
> 
> And maybe to add some logic, if the interval has less than N points, then to not to display it? Eg. a run of 30mins of runtime would show like only 1 point for an interval of 1 hour.
> 
> What do you think?

I think your ideas are very good. It's good to pre process all additional interval and store it in the db. 

One extra wish of me is an interval of 5 sec.

Of course, if it doesn't make sense to display only one point of an graph. If it isn't possible to divide the timespan of an testrun or the result of a division is less 2 then you shouldn't provide this calculated graph.

I don't know, if it make sense, to define the time interval in a general processing setting. Then the user has a chance to get a better performance in processing with less time intervals.

**Comment by ludeknovy** [comment] 2022-03-18 09:56
There must be an upper limit as well - long runs could be end up with too many points, and that would not make the chart very useful either.

**Comment by ludeknovy** [comment] 2022-03-28 08:26
Sneak preview. 
https://user-images.githubusercontent.com/13610612/160357325-9e449005-dccc-4e1a-b1cc-d7c13dc9bd49.mov

**Comment by MoritzSalein** [comment] 2022-03-28 11:47
> Sneak preview. https://user-images.githubusercontent.com/13610612/160357325-9e449005-dccc-4e1a-b1cc-d7c13dc9bd49.mov

Very nice :-)

**Comment by ludeknovy** [comment] 2022-04-19 09:04
@MoritzSalein  available in "latest" tag. To test it out, you will need to upgrade be, fe and migration services in docker-compsoe file.

**Comment by ludeknovy** [comment] 2022-04-29 05:57
Hi @MoritzSalein! By any chance, did you have time to try it out?

**Comment by MoritzSalein** [comment] 2022-05-04 09:35
Hi @ludeknovy I have tried out the change. The granularity is available. The graphs changes when I set a different granularity. But I have a problem with the tool tip for the data point of the selected granularity. I addition I have tool tips for data points that are not in the selected graph. In the first screenshot, you'll see a data point for the selection. The second screenshot will shown a data point outside the selection.
And I don't see the virtual users label ih the first screenshot.
![image](https://user-images.githubusercontent.com/83296020/166656441-020ac279-25fd-45c6-92f7-47541f648a87.png)
![image](https://user-images.githubusercontent.com/83296020/166656466-6e29a2cf-b1b7-4f2a-95d1-b771b0e481e4.png)

**Comment by ludeknovy** [comment] 2022-05-06 06:44
Hi @MoritzSalein. Thanks for the feedback. I am not able to reproduce this locally. From the screenshots, it looks like focus issue - 1) the virtual users line seems to be faded (disabled, inactive?) and thus not shown in the tooltip. 2) Actually, only the virtual users line seems to be active.

**Comment by csvtuda** [comment] 2022-05-06 13:26
I can confirm that there seem to be issues when hovering over the graph. I can either get labels for all datapoints _except_ the virutal users to show up, or the virtual users on their own without any of the other datapoints. It's quite erratic behaviour and hard to explain in screenshots. I recorded a little video in Firefox version 100.0 (😎):

https://user-images.githubusercontent.com/18561435/167140528-d22ebbc8-2780-4694-a7d3-da8a127c6f50.mp4

**Comment by ludeknovy** [comment] 2022-05-06 14:03
Hi @csvtuda ! I understand the issue, but still not able to reproduce it :|

I tried FF as well, and it behaves correctly - could you try another browser?

https://user-images.githubusercontent.com/13610612/167148465-74e5e3ce-2590-47f3-9b4e-6dc3fff3665c.mp4

**Comment by csvtuda** [comment] 2022-05-06 15:03
Yes, the issue also persists in Chrome, Version 101.0.4951.54 (64-Bit). In both browsers it only appears when using aggregation types other than `Auto`.
FYI: I'm using a local build of the JTL reporter with the following commits checked out:

- jtl: `6a1aa60`
- jtl-be: `80c24e6`
- jtl-fe: `d0b02d7`
- jtl-listener: `f35eaf1`
- jtl-scheduler: `f1f7bb1`

I just tried the dockerized version using `[...]:latest` everywhere and `v0.0.2` for the scheduler, but the issue still appears.

**Comment by MoritzSalein** [comment] 2022-05-09 06:29
@ludeknovy On my own installation I get the problem with Firefox, Edge and Chrome. The problem is not with the Auto aggregation. Only when I switch to another aggregation. 
My installation is completely fresh, without old data in the database. Could it a problem with my JMeter jtl-Data? I additionally collect the hostname in my jtl, because I ran the JMeter project in a master-slave installation.
I work with the following commits of the main branches:
jtl: `6a1aa60`
jtl-be: `80c24e6`
jtl-fe: `cee6faf`
jtl-listener: `f35eaf1`
jtl-scheduler: `f1f7bb1`

**Comment by csvtuda** [comment] 2022-05-09 15:56
Okay so I just tried again with anonymized request labels and an arbitrary IP for hostname and it worked fine, no issue whatsoever.

I then anonymized step-by-step and to me it looks like multiple host names are the cause. When I replace them with a single hostname, everything works smoothly.

I attached a mini report containing different host names
[results_mini.csv](https://github.com/ludeknovy/jtl-reporter/files/8653286/results_mini.csv)
.

**Comment by ludeknovy** [comment] 2022-05-10 07:50
@csvtuda Thanks! Now I am able to reproduce it.  👀

**Comment by ludeknovy** [comment] 2022-05-10 10:23
I hope I found it and should be fixed now.

**Comment by MoritzSalein** [comment] 2022-05-10 15:00
It works perfectly now on my installation. Thank you.

**Closed** 2022-05-10 15:00 UTC
