### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by Anakinn** [ludeknovy/jtl-reporter#35] opened 2021-04-02 12:10 UTC
Example provided not working:

If we follow this:

@events.init.add_listener
def on_locust_init(environment, **_kwargs):
    JtlListener(env=environment,  project_name="project name",
                scenario_name="scenario name",
                environment="tested envitonment"
                backend_url="http://IP_ADDRESS")

The error displayed will be:

SyntaxError: invalid syntax, missing comma after environment. If we add comma we will get another error probably because of syntax error: TypeError: __init__() got an unexpected keyword argument 'backend_url'

After changing 'backend_url' to backed_url no error displayed but only empty csv file generated, no jtl file in logs directory.

Am I doing something wrong here? What should backend_url be, URL of JTLReporter or something else?

I think that this project is very good but some clarification on how to use it would be good.

**Comment by ludeknovy** [comment] 2021-04-02 13:22
Hi @Anakinn!

Lets make the docs better!

You are right, in the readme example the comma is missing and there is a typo in the listener as well. Will fix them right away.

I will check the empty csv :/

**Comment by ludeknovy** [comment] 2021-04-02 13:34
@Anakinn Ok, I think I know where the issue is - it only works when running locust in distributed mode.

**Comment by Anakinn** [comment] 2021-04-02 13:56
@ludeknovy aha thanks I will try to run it in distributed mode then.

**Comment by ludeknovy** [comment] 2021-04-02 14:39
@Anakinn I will add the information about it into readme as well, thanks for pointing to it.

**Comment by Anakinn** [comment] 2021-04-02 14:47
I was able to get the file with distributed run. Now I am trying to send updates continuously and seeing some error about token, but token is present. When I sort it out I will share my findings.

**Comment by ludeknovy** [comment] 2021-04-02 16:51
@Anakinn what kind of error?

**Comment by Anakinn** [comment] 2021-04-06 07:15
> @Anakinn what kind of error?

Now everything is good with token but another error is popping out on end:
AttributeError: 'JtlListener' object has no attribute 'item_id'

And error present on test start:

 self.data_id = response["dataId"]
KeyError: 'dataId'

**Comment by ludeknovy** [comment] 2021-04-06 07:21
Thanks for sharing. I think I will add more logs and better error messages:) 

Are you sure you have the tokens set up correctly in `docker-compose.yml` ? It looks like, the two services cannot communicate properly.

I will try to retest it soon on my own, but already using it on one project and it works fine, but there might have been some copy paste mistake on my side....

**Comment by Anakinn** [comment] 2021-04-06 07:45
@ludeknovy  I would say you are right. I am getting 400 bad request from listener service, but not because of token:

{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":400,"payload":{"statusCode":400,"error":"Bad Request","message":"\"environment\" must be a string"},"headers":{}},"level":"error"}

Were you running tests on Linux machine or windows machine?

**Comment by ludeknovy** [comment] 2021-04-06 07:59
@Anakinn macos/linux only.

the environment should be fetched from the "host" you provide in your test automatically.
```
 "environment": self.env.host
```

**Comment by Anakinn** [comment] 2021-04-06 08:27
> @Anakinn macos/linux only.
> 
> the environment should be fetched from the "host" you provide in your test automatically.
> 
> ```
>  "environment": self.env.host
> ```

You are right. I figured that out and that variable is empty for some reason, and I hardcoded it in listener py file just to get it going. The problem is maybe that I am running the test on windows machine and it is not picking some variables as it should.
So when I hardcode environment: self.env.host in listener file it gets going but now I have issues with scenario id which is for some reason returning null when trying to insert in db. Will continue to debug.

**Comment by Anakinn** [comment] 2021-04-06 08:30
> > @Anakinn macos/linux only.
> > the environment should be fetched from the "host" you provide in your test automatically.
> > ```
> >  "environment": self.env.host
> > ```
> 
> You are right. I figured that out and that variable is empty for some reason, and I hardcoded it in listener py file just to get it going. The problem is maybe that I am running the test on windows machine and it is not picking some variables as it should.
> So when I hardcode environment: self.env.host in listener file it gets going but now I have issues with scenario id which is for some reason returning null when trying to insert in db. Will continue to debug.

Scenario id is my issue, Typo error :) With that thing hardcoded in listener file: "environment": self.env.host I was able to send reports from tests  :)

**Comment by ludeknovy** [comment] 2021-04-06 08:40
@Anakinn Great! Glad to hear that. I will double-check the `environment` later on other platforms as well. Btw. what locust version did you use?

Is there anything that we could add to readme to make the integration smoother?

**Comment by Anakinn** [comment] 2021-04-09 10:56
version: locust 1.4.3

everything is fine I did not know that it should be executed in distributed mode and that is something I think that should be in documentation.

**Comment by ludeknovy** [comment] 2021-04-09 10:59
@Anakinn thanks, will add a note about `distributed mode` into readme.

Can we close this?

**Closed** 2021-04-09 14:42 UTC
Labels: bug
